Rocket:
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$03,$CC,$00
    .byte $00,$3F,$C3,$00
    .byte $3C,$FF,$CC,$C0
    .byte $CC,$00,$00,$00
    .byte $3C,$FF,$FF,$F0
    .byte $00,$3F,$FF,$00
    .byte $00,$00,$00,$00
    .byte $00,$3F,$CF,$F3
    .byte $00,$CC,$C0,$00
    .byte $00,$3F,$CF,$CC
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00


