    align $100   ; ANTIC can only count to $FFF

Rocket:
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$03,$CC,$00
    .byte $00,$3F,$C3,$00
    .byte $3C,$FF,$CC,$C0
    .byte $CC,$00,$00,$00
    .byte $3C,$FF,$FF,$F0
    .byte $00,$3F,$FF,$00
    .byte $00,$00,$00,$00
    .byte $00,$3F,$CF,$F3
    .byte $00,$CC,$C0,$00
    .byte $00,$3F,$CF,$CC
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00


MissileRocket:
    .byte $00,$03,$C0,$00
    .byte $00,$03,$C0,$00
    .byte $00,$00,$00,$00
    .byte $00,$0F,$F0,$00
    .byte $00,$0F,$F0,$00
    .byte $00,$00,$00,$00
    .byte $00,$0F,$F0,$00
    .byte $00,$0F,$F0,$00
    .byte $00,$3F,$CC,$00
    .byte $00,$3F,$CC,$00
    .byte $00,$3F,$CC,$00
    .byte $00,$3F,$CC,$00
    .byte $00,$3F,$CC,$00
    .byte $00,$3F,$CC,$00
    .byte $0F,$00,$00,$F0
    .byte $0F,$3F,$FC,$F0
    .byte $3F,$CF,$F3,$FC
    .byte $3F,$CF,$F3,$FC
    .byte $FF,$CF,$F3,$FF
    .byte $FF,$C3,$C3,$FF
    
Enemy10:
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$FF,$33,$00
    .byte $03,$FF,$FC,$C0
    .byte $00,$00,$00,$00
    .byte $0F,$3F,$3F,$30
    .byte $0F,$3F,$3F,$30
    .byte $00,$00,$00,$00
    .byte $03,$FC,$FC,$C0
    .byte $03,$F3,$F3,$C0
    .byte $00,$00,$00,$00
    .byte $03,$FF,$F3,$C0
    .byte $03,$3F,$30,$C0
    .byte $03,$CF,$F3,$C0
    .byte $0C,$00,$00,$30
    .byte $00,$00,$00,$00
Enemy11:
    .byte $00,$00,$00,$00
    .byte $00,$00,$00,$00
    .byte $00,$FF,$33,$00
    .byte $03,$FF,$FC,$C0
    .byte $00,$00,$00,$00
    .byte $0C,$FC,$FC,$F0
    .byte $0C,$FC,$FC,$F0
    .byte $00,$00,$00,$00
    .byte $03,$CF,$CF,$C0
    .byte $03,$3F,$3F,$C0
    .byte $00,$00,$00,$00
    .byte $03,$FF,$F3,$C0
    .byte $03,$3F,$30,$C0
    .byte $03,$CF,$F3,$C0
    .byte $0C,$00,$00,$30
    .byte $00,$00,$00,$00
